''' CONSTANTS FILE '''

# Registration Constants
API_KEY = 'YOUR API KEY'
ALLOWED_FILE_TYPES = set(['pdf'])
FILE_PATH = 'YOUR FILE PATH'

#Database Constants
DB_NAME = 'YOUR DB NAME'
DB_USER_NAME = 'YOUR DB USER NAME'
DB_PASSWORD = 'YOUR DB PASSWORD'
DB_TABLE_NAME = 'YOUR DB TABLE NAME'
DB_HOST = 'localhost'